In [1]:
import warnings
import pandas as pd
import yfinance as yf
import pyfolio as pf
%matplotlib inline
warnings.filterwarnings('ignore')

/Users/terrencetrimuel/anaconda3/envs/dev/lib/python3.10/site-packages/pyfolio/pos.py:25: UserWarning: Module "zipline.assets" not found; multipliers will not be applied to position notionals.
  warnings.warn(

In [13]:
#input for stock ticker name
name = input()
#this is the start date entry yyyy-MM-DD
start = input()
#this is the end date entry yyyy-MM-DD
end = input()

In [14]:
#this is tthe function to bring in the data 
df= yf.download(name,start=start,end=end)
#this is to print the data 
df

[*********************100%%**********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2021-06-01,125.080002,125.349998,123.940002,124.279999,122.674835,67637100
2021-06-02,124.279999,125.239998,124.050003,125.059998,123.444756,59278900
2021-06-03,124.680000,124.849998,123.129997,123.540001,121.944389,76229200
2021-06-04,124.070000,126.160004,123.849998,125.889999,124.264030,75169300
2021-06-07,126.169998,126.320000,124.830002,125.900002,124.273895,71057600
...,...,...,...,...,...,...
2023-05-03,169.500000,170.919998,167.160004,167.449997,166.993195,65136000
2023-05-04,164.889999,167.039993,164.309998,165.789993,165.337723,81235400
2023-05-05,170.979996,174.300003,170.759995,173.570007,173.096512,113316400
2023-05-08,172.479996,173.850006,172.110001,173.500000,173.026688,55962800
2023-05-09,173.050003,173.539993,171.600006,171.770004,171.301422,45326900